version: '3.3'
services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    restart: unless-stopped
    env_file: .env
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/testData.sql:/docker-entrypoint-initdb.d/testData.sql
  ai:
    build: ./recommendations
    container_name: recommendation_module
    env_file: .env
    ports:
      - "5000:5000"
  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    volumes:
      - .m2:/root/.m2
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:7.0.11
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    volumes:
      - ./sonarqube/bitegarden-sonarqube-report-2.15.5.jar/:/opt/sonarqube/extensions/plugins/pdf.jar
    ports:
      - "9000:9000"
volumes:
  db:
networks:
  default:
    driver: bridge