spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: foodzillabackend
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    username: ${MYSQL_USER:#{user}}
    password: ${MYSQL_PASSWORD:#{password}}
    url: ${MYSQL_URL}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect