spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    username: ${TEST_MYSQL_USER}
    password: ${TEST_MYSQL_PASSWORD}
    url: ${TEST_MYSQL_URL}
  data:
    redis:
      port: ${TEST_REDIS_PORT}
      run-sync-task: false