name: Java CI with Maven

env:
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_URL: jdbc:mysql://localhost:${MYSQL_LOCAL_PORT}/${MYSQL_DATABASE}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
      redis:
        image: redis
        ports:
          - 6380:6379
    steps:
      - uses: actions/checkout@v2
      - name: Init database
        run: |
          mysql -h 127.0.0.1 -u user -ppassword db < src/main/resources/init.sql
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17-ea'
          distribution: 'temurin'
          cache: maven
      - name: Build backend application
        run: mvn install --file pom.xml